### ISSUE TITLE
ignores are not working

### ISSUE THREAD

**Issue by soundyogi** [diffsky/LOTS#12]
did work a while ago no it does not even ignore node_modules  (which it should by default)

![screenshot from 2017-03-23 15-28-38](https://cloud.githubusercontent.com/assets/3201046/24252387/aa595bc0-0fdd-11e7-8edd-9f0f7fe3cf84.png)

**Comment by diffsky** [comment]
This was working for me until I added in an `--ignore` flag and the default ignores were being clobbered. I don't see a flag being passed in on the screenshot (maybe an alias?) but hopefully this resolves the issue.

```
+ lots@1.5.0
```

**Comment by soundyogi** [comment]
I think it is a problem with grep?
Maybe my version is not right?
I cannot exclude anything and it always searches the node_modules folder.
Thanks!

**Comment by diffsky** [comment]
You can `console.log` the value of `cmd` here: https://github.com/diffsky/LOTS/blob/master/lib/lots.js#L67 to see the grep command being run.

```
tickets: 'grep -H -n -R -I "\\!" *  --exclude \'node_modules/*\' | grep "#"'
```

If you remove the escaping backslashes, you should get:
```
grep -H -n -R -I "\\!" *  --exclude 'node_modules/*' | grep "#"
```

Try running that command directly and see what you get.

My version of grep:
```
$ grep --version
grep (BSD grep) 2.5.1-FreeBSD
```
