### ISSUE TITLE
add github integration

### ISSUE THREAD

**Issue by diffsky** [diffsky/LOTS#5]

**Comment by soundyogi** [comment]
So, how would one start doing that?
(Just some Hints / Ideas?)

**Comment by diffsky** [comment]
Something like...

With an api token (that LOTS could generate via credentials or it could be passed to LOTS directly in config) it could talk to the github api. The tricky part is the convention of matching a LOTS issue to a github issue (perhaps the github issues could be tagged as "LOTS"). 

The LOTS web interface might have a button to prompt the user to create a github issue for a found LOTS ticket, or if one exists show a link to the issue on github (LOTS would have to pull all issues tagged "LOTS" and try and match on the ticket title). 

LOTS is still on my radar, but I have a lot of other things happening at the moment so I haven't had the time to look at this (obviously!)

**Comment by soundyogi** [comment]
Okay cool I will look into that!

Yeah man all your projects are awesome, I will try to help you as much as I can!

**Comment by diffsky** [comment]
It's worth developing the issue syncing system as a separate project that LOTS could make use of. It could be passed a pattern of issues to look for and validate them against github.
