### ISSUE TITLE
ignore only files?

### ISSUE THREAD

**Issue by soundyogi** [diffsky/LOTS#8]
is it possible to ignore only files instead of folders using "-i"  ?

**Comment by diffsky** [comment]
I've updated the `-i` options to take a pattern instead of a directory, this should allow you to specify files or directories (as `dir/*.*`) as indicated in the stackoverflow link.

**Comment by soundyogi** [comment]
awesome! thx

**Comment by diffsky** [comment]
There have been some big changes to how LOTS works under the hood. Let me know if you have any issues on windows (which I don't have a way to test)
