### ISSUE TITLE
LOTS on windows machines

### ISSUE THREAD

**Issue by soundyogi** [diffsky/LOTS#9]
Hey, 
this is probably the wrong place but this is how I got LOTS to work on windows:

### Install GitBash and update grep
Install GitBash:
https://msysgit.github.io/

Download Grep:
http://sourceforge.net/projects/ezwinports/files/grep-2.10-w32-bin.zip/download

Extract to *Git install directory*/bin 
(Probably C:Program Files/Git)

**Comment by diffsky** [comment]
Cool, thanks for the info! I'll leave it here (but close the issue) for others to find.
